core: remove interrupt test PTA
The interrupt test PTA does not support CFG_TEE_CORE_NB_CORE > 7 and
there is a compilation warning when it is > 31:

 $ make -s CFG_TEE_CORE_NB_CORE=32 CFG_TEE_CORE_EMBED_INTERNAL_TESTS=y \
           CFG_WERROR=y
 In file included from core/include/kernel/interrupt.h:10,
                  from core/pta/tests/interrupt.c:7:
 core/pta/tests/interrupt.c: In function ‘test_sgi’:
 lib/libutils/ext/include/util.h:117:44: error: left shift count >= width of type [-Werror=shift-count-overflow]
   117 | #define SHIFT_U32(v, shift) ((uint32_t)(v) << (shift))
       |                                            ^~
 core/pta/tests/interrupt.c:97:18: note: in expansion of macro ‘SHIFT_U32’
    97 |        (uint8_t)(SHIFT_U32(1, CFG_TEE_CORE_NB_CORE) - 1));
       |                  ^~~~~~~~~
 cc1: all warnings being treated as errors

Since this PTA is unused, remove it.

Signed-off-by: Jerome Forissier <jerome@forissier.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>
Acked-by: Etienne Carriere <etienne.carriere@linaro.org>