libutee: arm64: update register accessor macros to support Clang
When building a 64-bit TA that includes <arm64_user_sysreg.h>, Clang
complains about ASM operand width:

 lib/libutee/include/arm64_user_sysreg.h:31:1: error: value size does not match register size specified by the constraint and modifier [-Werror,-Wasm-operand-widths]
 DEFINE_REG_READ_FUNC_(cntfrq, uint32_t, cntfrq_el0)
 ^
 lib/libutee/include/arm64_user_sysreg.h:20:42: note: expanded from macro 'DEFINE_REG_READ_FUNC_'
         asm volatile("mrs %0, " #asmreg : "=r" (val));  \
                                                 ^
 lib/libutee/include/arm64_user_sysreg.h:31:1: note: use constraint modifier "w"
 lib/libutee/include/arm64_user_sysreg.h:20:20: note: expanded from macro 'DEFINE_REG_READ_FUNC_'
         asm volatile("mrs %0, " #asmreg : "=r" (val));  \
                           ^
Let's apply the same fix as in commit 16e2153c57f0 ("core: arm64:
update register accessor macros to support Clang").

Signed-off-by: Jerome Forissier <jerome@forissier.org>
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
Acked-by: Etienne Carriere <etienne.carriere@linaro.org>